import { RecentVisitor } from "./security";

export const mockRecentVisitors: RecentVisitor[] = [
  {
    id: "v1",
    name: "Amit Sharma",
    type: "Family",
    unit: "A-101",
    status: "in",
    timestamp: "10:15 AM",
    purpose: "Family visit",
    phone: "9876543210",
    notes: "Brother of tenant",
    photo: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "v2",
    name: "Swiggy Delivery",
    type: "Delivery",
    unit: "B-202",
    status: "out",
    timestamp: "11:30 AM",
    checkoutTime: "11:45 AM",
    duration: "15 min",
    purpose: "Food delivery",
    phone: "9876543211",
  },
  {
    id: "v3",
    name: "Lakshmi",
    type: "Maid",
    unit: "C-301",
    status: "in",
    timestamp: "09:00 AM",
    purpose: "Daily cleaning",
    phone: "9876543212",
    notes: "Regular maid, comes daily",
  },
  {
    id: "v4",
    name: "Electrician",
    type: "Vendor",
    unit: "A-102",
    status: "out",
    timestamp: "08:45 AM",
    checkoutTime: "10:30 AM",
    duration: "1 hr 45 min",
    purpose: "Repair work",
    phone: "9876543213",
    notes: "Fixed AC unit",
  },
  {
    id: "v5",
    name: "Priya Patel",
    type: "Visitor",
    unit: "B-201",
    status: "in",
    timestamp: "12:00 PM",
    purpose: "Meeting",
    phone: "9876543214",
  },
];
